### ISSUE TITLE
Signup a user does not receive email for verification

### ISSUE THREAD

**Issue by kinyat** [aws/amazon-cognito-identity-js#516]
I followed the example provided by AWS for registration.

The user is created however it is not confirmed.

![](https://i.stack.imgur.com/Tm2QZ.png)

I expected that when I call signup(), it will automatically send an email to the user but it does not seems like it.

Would love to know how to get the email confirmation works.

Related CloudFormation for userPool
```yaml
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: 
          Fn::Sub: ${{self:custom.userPool}}
        AliasAttributes:
          - email
          - phone_number
          - preferred_username
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        AutoVerifiedAttributes: 
          - email
          #- phone_number
        MfaConfiguration: "OPTIONAL"
        SmsConfiguration:
          ExternalId:
            Fn::Sub: ${{self:custom.namespace}}-external
          SnsCallerArn: 
            Fn::GetAtt: [ SNSRole, Arn ]
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: false
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
          - Name: phone_number
            AttributeDataType: String
            Mutable: false
            Required: false
```
